version: "2"

services:
  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres@postgres/webapp_dev
      PORT: 8000

  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: webapp_dev
      POSTGRES_HOST_AUTH_METHOD: trust
