version: "2"

services:
  backend:
    build: .
    ports:
      - 8000:8000
      - 9229:9229 # debugger port
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    command: npm run start:docker
    depends_on:
      - mysql
    environment:
      DATABASE_URL: mysql://root:password@mysql:3306/pitchtrainer_test
      PRISMA_CONFIG:
        port: 8000
        databases:
          default:
            connector: mysql
            host: db
            port: 3306
            user: root
            password: password
            migrations: true

  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: password
